### PR TITLE
MCP23008 I2C backpack example

### PR DESCRIPTION
**Pull request by eLvErDe**
Hello,

I had an hard time getting the MCP23008 based backback working with i2c and a basic 16x2 LCD.
So please find attached a simple example that just work :-)

Regards, Adam.

[1] https://www.adafruit.com/products/292

### CODE REVIEW

**Comment by Swinkid** [comment]
If it helps, if you change "6" to "7" when initializing the LCD it will turn the backlight on without grounding. Obviously, not sending data over correctly, but it shows the backlight it wired up to the chip

**Comment by xprojectmanager** [comment]
Using your code, I'm able to activate backlight 

`lcd = LCD.Adafruit_CharLCD(1, 2, 3, 4, 5 , 6, lines, cols, gpio=gpio, backlight=7, `invert_polarity=False)`

**Comment by eLvErDe** [comment]
Nice :) It's even a better example now. Adafruit ?

**Comment by kattni** [comment]
We've added support for the Pi Plate to a newer version of this library.

We're going to be deprecating this library in favor of this one: https://github.com/adafruit/Adafruit_CircuitPython_CharLCD

That library is available on PyPI for you to `pip3 install adafruit-circuitpython-charlcd` and use on Raspberry Pi thanks to the Adafruit-Blinka library which should install automatically along with the other dependencies needed for using `charlcd`.  Please see the [documentation](https://circuitpython.readthedocs.io/projects/charlcd/en/latest/) for API and usage examples. There are Raspberry Pi-specific examples in the `examples/` folder in the repo.

**Pull request closed without merging**
